# Generated by Django 3.2.4 on 2021-07-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_sunject_homework_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='is_finisehd',
            new_name='is_finished',
        ),
    ]
